<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerELyc1iG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerELyc1iG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerELyc1iG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerELyc1iG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerELyc1iG\App_KernelDevDebugContainer([
    'container.build_hash' => 'ELyc1iG',
    'container.build_id' => '5baceebf',
    'container.build_time' => 1602528368,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerELyc1iG');
