<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTYZYfB5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTYZYfB5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTYZYfB5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTYZYfB5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTYZYfB5\App_KernelDevDebugContainer([
    'container.build_hash' => 'TYZYfB5',
    'container.build_id' => '8fc563d3',
    'container.build_time' => 1602940839,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTYZYfB5');
